create sequence UserInfo_SEQ start with 1 increment by 50;
create table UserInfo (dateOfBirth varchar(255), firstName varchar(255), gender varchar(255), lastName varchar(255), password varchar(255), phoneNumber varchar(255), roles varchar(255), userID varchar(255) not null, primary key (userID));
create table hibernate_sequences (next_val bigint, sequence_name varchar(255) not null, primary key (sequence_name));
insert into hibernate_sequences(sequence_name, next_val) values ('default',0);
create table UserInfo (dateOfBirth varchar(255), firstName varchar(255), gender varchar(255), lastName varchar(255), password varchar(255), phoneNumber varchar(255), roles varchar(255), userID varchar(255) not null, primary key (userID));
create table hibernate_sequences (next_val bigint, sequence_name varchar(255) not null, primary key (sequence_name));
insert into hibernate_sequences(sequence_name, next_val) values ('default',0);
create table UserInfo (dateOfBirth varchar(255), firstName varchar(255), gender varchar(255), lastName varchar(255), password varchar(255), phoneNumber varchar(255), roles varchar(255), userID varchar(255) not null, primary key (userID));
create table hibernate_sequences (next_val bigint, sequence_name varchar(255) not null, primary key (sequence_name));
insert into hibernate_sequences(sequence_name, next_val) values ('default',0);
create table UserInfo (dateOfBirth varchar(255), firstName varchar(255), gender varchar(255), lastName varchar(255), password varchar(255), phoneNumber varchar(255), roles varchar(255), userID varchar(255) not null, primary key (userID));
create table hibernate_sequences (next_val bigint, sequence_name varchar(255) not null, primary key (sequence_name));
insert into hibernate_sequences(sequence_name, next_val) values ('default',0);
create table UserInfo (userID integer not null, dateOfBirth varchar(255), firstName varchar(255), gender varchar(255), lastName varchar(255), pass varchar(255), phoneNumber varchar(255), roles varchar(255), primary key (userID));
create sequence UserInfo_SEQ start with 1 increment by 50;
create table UserInfo (userID integer not null, dateOfBirth varchar(255), firstName varchar(255), gender varchar(255), lastName varchar(255), pass varchar(255), phoneNumber varchar(255), roles varchar(255), primary key (userID));
create sequence UserInfo_SEQ start with 1 increment by 50;
create table UserInfo (userID integer not null, dateOfBirth timestamp(6), firstName varchar(255), gender varchar(255), lastName varchar(255), pass varchar(255), phoneNumber varchar(255), roles varchar(255), primary key (userID));
create sequence UserInfo_SEQ start with 1 increment by 50;
create table UserInfo (phoneNumber integer, userID integer not null, dateOfBirth timestamp(6), firstName varchar(255), gender varchar(255), lastName varchar(255), pass varchar(255), roles varchar(255), primary key (userID));
